using System;

namespace WaveLib.AudioMixer
{
	public enum MMErrors
	{
		MMSYSERR_NOERROR = 0,
		MMSYSERR_ERROR = 1,
		MMSYSERR_BADDEVICEID = 2,
		MMSYSERR_NOTENABLED = 3,
		MMSYSERR_ALLOCATED = 4,
		MMSYSERR_INVALHANDLE = 5,
		MMSYSERR_NODRIVER = 6,
		MMSYSERR_NOMEM = 7,
		MMSYSERR_NOTSUPPORTED = 8,
		MMSYSERR_BADERRNUM = 9,
		MMSYSERR_INVALFLAG = 10,
		MMSYSERR_INVALPARAM = 11,
		MMSYSERR_HANDLEBUSY = 12,
		MMSYSERR_INVALIDALIAS = 13,
		MMSYSERR_BADDB = 14,
		MMSYSERR_KEYNOTFOUND = 15,
		MMSYSERR_READERROR = 16,
		MMSYSERR_WRITEERROR = 17,
		MMSYSERR_DELETEERROR = 18,
		MMSYSERR_VALNOTFOUND = 19,
		MMSYSERR_NODRIVERCB = 20,
		MMSYSERR_LASTERROR = 21,
		MMSYSERR_MOREDATA = 21,
		WAVERR_BADFORMAT = 32,
		WAVERR_STILLPLAYING = 33,
		WAVERR_UNPREPARED = 34,
		WAVERR_LASTERROR = 35,
		WAVERR_SYNC = 35,
		MIXERR_INVALLINE = 1024,
		MIXERR_INVALCONTROL = 1025,
		MIXERR_INVALVALUE = 1026,
		MIXERR_LASTERROR = 1026
	}
}